name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Step 1: Gerar a animação da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LyizDuarte
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 2: Publicar no GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Passo adicional para garantir permissões de push se necessário:
      - name: Ensure push permissions
        run: git config --global user.email "looduarte21@gmail.com" && git config --global user.name "GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
